[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.crop-insurance-core]
path = 'contracts/crop-insurance-core.clar'
clarity_version = 3
epoch = 3.0

[contracts.crop-insurance-governance]
path = 'contracts/crop-insurance-governance.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
